### ISSUE TITLE
Paste image to upload it

### ISSUE THREAD

**Issue by LouWii** [ldidry/lutim#23]
Hi !
One improvement I think would be great is the ability to paste (ctrl + v) image to upload it.
Like on http://ctrlv.in/ or http://snag.gy/

**Comment by ldidry** [comment]
I can't find a true cross-browser solution. I guess we'll have to wait a while.

I close this issue but, please, reopen it if you find a solution.

**Comment by machado2** [comment]
I've seen this feature working well on Discourse, I have some links for their discussion on this:

The discussion topic about pasting topics, from when they implemented it:
https://meta.discourse.org/t/ability-to-paste-an-image-into-the-compose-form/1582/1

An example snippet:
https://gist.github.com/Buildstarted/4577472

The current javascript file in Discourse for their composer, that is the window that implements it:
https://github.com/discourse/discourse/blob/master/app/assets/javascripts/discourse/components/composer-editor.js.es6

The commit that fixed a problem with firefox:
https://github.com/discourse/discourse/commit/e573ea29f3e2c827f07e20ff01c1f43e61839a1a

**Comment by ldidry** [comment]
MR in progress on https://framagit.org/luc/lutim/merge_requests/5
