### ISSUE TITLE
Able to upload SVG

### ISSUE THREAD

**Issue by steveschnepp** [ldidry/lutim#47]
As bitmapped images are so 2012, it would be very nice to be able to upload SVG also.

**Comment by ldidry** [comment]
Seems that iframes in svg breaks upload :stuck_out_tongue: so I don't have to worry :wink:

**Comment by steveschnepp** [comment]
@ldidry :+1:

**Comment by ldidry** [comment]
This is not in production yet. I'm late (if I look at my schedule), but hey! Even FOOS developers needs some rest :wink:
