### ISSUE TITLE
Allow command line option to change location of the database

### ISSUE THREAD

**Issue by philalex** [ldidry/lutim#48]
Hi!
one improvement is to permit to change the location of the database (`lutim.db`) with one command line parameter, the default value is the actual path.

This parameter will improve upgrade process when lutim is used in Docker: you only have to build the new docker and pass database and images directory as parameters to the new  docker.

**Comment by Kharec** [comment]
We can also add a parameter "db_path" in lutim.conf, what do you think ?

**Comment by ldidry** [comment]
yes, db_path. Now the question : absolute path or relative path? And if relative, relative to what? I think that relative path beginning from lutim root directory would be the best shot. What do you think?

**Comment by Kharec** [comment]
I think relative path to lutim root is great ! I'll work on that tonight !

**Comment by Kharec** [comment]
Here is a start of patch. 

diff --git a/lib/LutimModel.pm b/lib/LutimModel.pm
index 09c9b84..fbdc9c5 100644
--- a/lib/LutimModel.pm
+++ b/lib/LutimModel.pm
@@ -1,8 +1,21 @@
 package LutimModel;

+use Mojo::Base 'Mojolicious';
+
+sub getdbpath {
+   my $self = shift;
+   my $config = $self->plugin('Config', {
+       file => '../lutim.conf',
+       default => {
+           db_path => 'lutim_dbpathOK.db'
+       }
+   });
+   return $config->{db_path}; # just to see if it's working
+}
+
 # Create database
 use ORLite {
-      file => 'lutim.db',
+      file => getdbpath(),
       unicode => 1,
       create => sub {
           my $dbh = shift;
diff --git a/lutim.conf.template b/lutim.conf.template
index 0860055..cd4ffbf 100644
--- a/lutim.conf.template
+++ b/lutim.conf.template
@@ -18,6 +18,9 @@
     ################
     # Lutim settings
     ################
+	# define a path to the SQLite database, which is relative to lutim root.
+	# default is ./script/
+    # db_path =

     # put a way to contact you here and uncomment it
     # mandatory

**Comment by ldidry** [comment]
```
# default is ./script/
```

I'd prefer the root of Lutim, since it's where it is right now.

**Comment by Kharec** [comment]
OK, I take care of that.

**Comment by ldidry** [comment]
Fixed in e1840e96
