### ISSUE TITLE
IO::Socket::SSL 1.84 required for TLS support

### ISSUE THREAD

**Issue by maniackcrudelis** [ldidry/lutim#49]
Salut,

une erreur survient lors de l'import d'une image depuis un site en https. Erreur qui ne se pose pas depuis lut.im.

L'import est impossible et le log indique
```
[Thu Feb  5 21:17:48 2015] [warn] [DOWNLOAD ERROR]{
  "message" => "IO::Socket::SSL 1.84 required for TLS support"
}
```
Tout fonctionne normalement avec une image en http en revanche.

**Comment by ldidry** [comment]
Rajoute 
```
requires "IO::Socket::SSL";
```
dans ton cpanfile et fais `carton install`.

C'est une erreur de ma part. Je croyais pourtant l'avoir corrigé. Zut, désolé :-(

**Comment by maniackcrudelis** [comment]
Ok, c'est ce qu'il me semblait avoir compris de l'ami google.
Je patch ça de mon côté pour le moment.

Je te remercie de tes réponses rapides ;)
