### ISSUE TITLE
Droits au démarrage en service

### ISSUE THREAD

**Issue by maniackcrudelis** [ldidry/lutim#50]
Salut,

je reviens t'embêter avec un autre petit problème.
Hypnotoad est censé démarrer sur les droits de l'user indiqué dans le fichier de conf, soit www-data. Mais ```/etc/init.d/lutim start``` ne fonctionne pas (sans rien trouver dans les logs à ce sujet), je ne peux démarrer qu'avec ```sudo /etc/init.d/lutim start``` ou ```sudo service lutim start```. Mais dans ces derniers cas, le fichier lutim.db et le dossier tmp sont créés avec les droits root ce qui provoque une erreur de droit de la part d'hypnotoad.

Je me retrouve obligé de modifier le script lutim.init en ajoutant ```sudo -u www-data``` en début de ligne 52.
https://github.com/ldidry/lutim/blob/master/utilities/lutim.init#L52

Dans ce cas, le serveur démarre correctement avec les bons droits et tout fonctionne. Est-ce bien normal?
J'ajoute, c'est peut-être lié, que le dossier lutim dans son ensemble appartient à www-data.

**Comment by ldidry** [comment]
Pour qu'hypnotoad puisse changer d'utilisateur pour les threads, il faut que ce soit `root` qui lance hypnotoad.

Donc oui, c'est normal :-)

**Comment by maniackcrudelis** [comment]
Ok, mais dans la config actuelle. En démarrant en root, hypnotoad ne peut pas écrire dans la bdd car elle appartient à root et non www-data.

**Comment by ldidry** [comment]
Ah oui, effectivement, c'est ballot. Mais généralement, je fais un `chown -R www-data:www-data lutim`, c'est pour ça que je n'avais jamais vu.
