### ISSUE TITLE
API JSON-response 'short' and 'real_short'

### ISSUE THREAD

**Issue by Thor77** [ldidry/lutim#51]
Hey,
whats the different between 'real_short' and 'short' in the json-response from the API?
It looks like URLs built with API-Url + 'real_short'-token doesn't work for the official lutim instance (on my own instance they work without any problems)!

**Comment by ldidry** [comment]
`real_short` is the image identifier (random characters) and `short` are the concatenation of `real_short`+ / + the encryption key.

As the official instance always encrypts the images, you only get an encrypted file if you download  API-Url + 'real_short'-token.

**Comment by Thor77** [comment]
Thanks for the explanation!
Maybe there should be a "JSON-Response"-section in the README?
I cant imagine i'm the first, who doesnt know whats the difference.

**Comment by ldidry** [comment]
Yep, you're right. I have a lot of work to do on Lutim but have no time right now. Will try to work on it in a few weeks.
