### ISSUE TITLE
Server error

### ISSUE THREAD

**Issue by matlink** [ldidry/lutim#53]
Sometimes when acceding my lutim instance via reverse proxy of nginx, I got a server error with the big unidino.
Is there a way to get where the issue is from ?
Thanks.

**Comment by matlink** [comment]
Well restarting lutim service did the trick

**Comment by ldidry** [comment]
Have a look at log/production.log, that' not normal.

**Comment by matlink** [comment]
Well it's resolved now, after restart lutim service
