### ISSUE TITLE
Error while trying to modify the image

### ISSUE THREAD

**Issue by matlink** [ldidry/lutim#54]
After an image upload, clicking on the "let's go" button pops me a JS window saying "Error while trying to modify the image". When looking at the dev console, there is an HTTP request (even if my web server is on https only) blocked cause of the mixed content (firefox).

**Comment by ldidry** [comment]
Did you set the header `X-Forwarded-Proto` to https in you reverse proxy configuration ?

**Comment by matlink** [comment]
I don't have any line like that.

**Comment by matlink** [comment]
Great, did the trick ! Thanks a lot !
