### ISSUE TITLE
Subfolder requests

### ISSUE THREAD

**Issue by matlink** [ldidry/lutim#56]
I got an issue : my lutim instance is under a subfodler of my domain : 

     domain.org/lutim

and the problem is that img,css and packed files are retrieved via domain.org/{img,css,packed} and i want the to be retrieved via the domain.org/lutim/{img,css,packed} urls. Can it be done ?

**Comment by ldidry** [comment]
It will be ok when I will merge the "proxy" branch of Lutim. You can test it if you want:
```
git clone https://github.com/ldidry/lutim
cd lutim
git checkout -b proxy origin/proxy
```

I am *very* late for merging that branch since I've got a lot of work, so I can't tell you when it will be ok to come back to master, sorry.

**Comment by ldidry** [comment]
I forgot, there is a new setting in lutim.conf:
```
    url_sub_dir       => '/lutim/',
```

**Comment by matlink** [comment]
I got a 404 when acceding the lutim path. Where can I see logs for acceded urls ?

**Comment by ldidry** [comment]
In the `log` directory. If you run lutim with hypnotoad, it is `production.log`, if it is with morbo (the development server) it is `development.log`.

**Comment by matlink** [comment]
It gives me only [info] messages, or [error] when it cannot access db for example. No trace of file/page not found.

**Comment by ldidry** [comment]
Can you provide a sample of the log ? If it says that it cannot write to db, it must be because the hypnotoad user set in lutim.conf (default to www-data) has no rights to write in the lutim folder.

**Comment by matlink** [comment]
Well db error has been fixed, reinstalling then posting news there.

**Comment by matlink** [comment]
[Mon Mar  9 21:48:31 2015] [info] Built asset for index.css: /var/www/lutim/public/packed/index-b11f83695a6317325810cc8f7a96ea32.css
[Mon Mar  9 21:48:31 2015] [info] Built asset for stats.css: /var/www/lutim/public/packed/stats-b2729272af2daf16727fa845d0e853e5.css
[Mon Mar  9 21:48:31 2015] [info] Built asset for about.css: /var/www/lutim/public/packed/about-e0db21b69a29b61dcc9b08c29c617636.css
[Mon Mar  9 21:48:31 2015] [info] Built asset for index.js: /var/www/lutim/public/packed/index-c013d33e6e5c539d04b1bb4ca825d0c1.js
[Mon Mar  9 21:48:31 2015] [info] Built asset for stats.js: /var/www/lutim/public/packed/stats-33bad45fd6a7ab2338d2681b76fbfe26.js
[Mon Mar  9 21:48:31 2015] [info] Built asset for freeze.js: /var/www/lutim/public/packed/freeze-e1ed5d112061ebc59ee3a1b9493f7d31.js
[Mon Mar  9 21:48:32 2015] [info] Listening at "http://127.0.0.1:8095".
[Mon Mar  9 21:48:32 2015] [info] Manager 18744 started.
[Mon Mar  9 21:48:32 2015] [info] Creating process id file "/var/www/lutim/script/hypnotoad.pid".

**Comment by ldidry** [comment]
Seems normal to me. Is the problem resolved?

**Comment by matlink** [comment]
No I still get a "page not found" when accessing to the domain.org/lutim/ folder. I got a blue background with stylesheet from lutim.

**Comment by matlink** [comment]
Well sounds like reinstallation did the trick. 
I'm gonna close for now till I get some news or error incomming :)
Thanks for help, it's a great project and you're really reactive, I love !
