### ISSUE TITLE
Allow image consulting publicly

### ISSUE THREAD

**Issue by matlink** [ldidry/lutim#57]
I'm packaging lutim for yunohost and I want to make uploaded images publicly accessible. 
I'm looking for a way to determine which URL is an image in order to not request HTTP credentials. 
Do you know a way ?

**Comment by ldidry** [comment]
You're not the first who want to package Lutim for Yunohost :smile:. Please have a look at issue #46

**Comment by ldidry** [comment]
I close the issue since it's a duplicate (and resolved in the soon-merged proxy branch)
