### ISSUE TITLE
index_url dans la page de stats

### ISSUE THREAD

**Issue by maniackcrudelis** [ldidry/lutim#58]
Bonjour,

Je rencontre une erreur, peut-être liée à la modification des sous-dossiers.
Sur la page des stats, le bouton "Retour à la page d'accueil" pointe sur domain.tld/lutim/index_url, il semblerais que la variable ne soit pas interprétée.

Et bien évidemment, je ne vois que le bout de la queue du raptor...

J'ai essayé de bidouiller un peu le fichier des stats
https://github.com/ldidry/lutim/blob/master/templates/stats.html.ep#L13
Mais je ne connais pas ce langage et ça ne semble pas incorrect à première vue. Et en faisant ces modifications, j'ai bien retrouvé le raptor, mais j'ai du le rendre malade, car il s'est mis à vomir un arc-en-ciel!

**Comment by ldidry** [comment]
Le bout de la queue, c'est une erreur 404, le vomi arc-en-ciel, c'est une erreur 500. Je vais essayer de voir ça.

**Comment by maniackcrudelis** [comment]
C'est tellement plus charmant un vomi de raptor qu'un simple 500 ;)

**Comment by ldidry** [comment]
En fait, je vois ce que c'est (enfin, je pense). Remplace
```
<%= link_to index_url => ( class => "btn btn-primary btn-lg" ) => begin %><%=l 'back-to-index' %><% end%>
```
par
```
<a href="<%= index_url %>" class="btn btn-primary btn-lg"><%=l 'back-to-index' %></a>
```

**Comment by ldidry** [comment]
Pis dis-moi si ça règle le pb :smiley:

**Comment by maniackcrudelis** [comment]
Bien joué, c'est ça.
Ça fonctionne parfaitement.
Merci ;)

**Comment by ldidry** [comment]
On va laisser l'issue ouverte, histoire que je pense à le modifier.

**Comment by maniackcrudelis** [comment]
Oui c'est pas faux, j'avais oublié ce détail important ! 
Et je crois que tu as le même bug sur la page about.

**Comment by ldidry** [comment]
C'est réglé dans la branche proxy, qui sera bientôt intégrée.
