### ISSUE TITLE
L'installation de carton fait planter postgrey

### ISSUE THREAD

**Issue by maniackcrudelis** [ldidry/lutim#59]
Salut

l'installation de carton via ```cpan carton``` provoque un plantage de postgrey (après redémarrage du service) sur 'Socket.pm'
Ce qui implique que plus aucun mail extérieur n'atteint le serveur!

postgrey renvoi cette erreur:
```Insecure dependency in socket while running with -T switch at /usr/lib/perl/5.14/IO/Socket.pm line 80.```

Le log du setup si ça peut servir:
http://hastebin.com/fofisasiqi.md

**Comment by maniackcrudelis** [comment]
Passer par apt-get install carton ne fait pas planter postgrey. Mais le service lutim ne peux pas démarrer car il ne trouve pas Mojolicious::Plugin::AssetPack::Preprocessor::Css:.

Or celui-ci se trouve bien dans 'lutim/local/lib/perl5/Mojolicious/Plugin/AssetPack/Preprocessor/'. Mais ce n'est pas dans le path.

Le message d'erreur:
```Can't load application from file "/var/www/lutim/script/lutim": Can't load application from file "/var/www/lutim/script/application": Could not load Mojolicious::Plugin::AssetPack::Preprocessor::Css: Can't locate Mojolicious/Plugin/AssetPack/Preprocessor/Css.pm in @INC (@INC contains: /var/www/lutim/script/../lib /var/www/lutim/script/../lib local/lib/perl5/i486-linux-gnu-thread-multi-64int local/lib/perl5 . /usr/share/perl/5.14 /usr/lib/perl/5.14) at (eval 73) line 1, <DATA> line 2231.```

**Comment by ldidry** [comment]
Le plantage de postgrey n'est pas aberrant, puisque Carton va avoir besoin de certains modules Perl dans certaines versions, tout comme postgrey, et paf, conflit.  
Du coup, effectivement, avec `apt-get install carton`, il n'y aura pas le problème.

Pour le preprocessor, essaye de faire : 
```
rm -rf local
carton install
```

**Comment by maniackcrudelis** [comment]
En ajoutant
```BEGIN { unshift @INC, "$FindBin::Bin/../local/lib/perl5" }``` à script/lutim, il trouve Css.pm mais ne trouve pas CSS/Minifier/XS.pm
Pourtant celui-ci est dans ```local/lib/perl5/i486-linux-gnu-thread-multi-64int```, qui est bien dans le path cette fois-ci.

Il est a noter que les bugs que je cite à présent proviennent d'une nouvelle install qui n'a pas fait de cpan Carton auparavant.

Je tente à nouveau carton install...

Même erreur sur Css.pm, script/Lutim n'a pas été touché par carton install.

**Comment by ldidry** [comment]
Installe le module via les dépôts
```
apt-get install  libcss-minifier-xs-perl
```

Est-ce que tu es sûr que carton install n'avait pas retourné d'erreur ?

**Comment by maniackcrudelis** [comment]
Aucune erreur de carton.
Et:
```Successfully installed CSS-Minifier-XS-0.09```

Après installation de libcss-minifier-xs-perl, aucune différence.
Je m'attendais à une autre erreur de dépendance...

**Comment by maniackcrudelis** [comment]
Je suis parvenu à faire démarrer le service en ajoutant ces 2 lignes a script/lutim
```BEGIN { unshift @INC, "$FindBin::Bin/../local/lib/perl5" }
BEGIN { unshift @INC, "$FindBin::Bin/../local/lib/perl5/i486-linux-gnu-thread-multi-64int" }```

Il faudrait vérifier si tu peux les ajouter de façon plus pérenne et si ça fonctionne même dans le cas d'un cpan Carton.
Car en l'état, via apt-get carton, ça ne fonctionne pas sans cet ajout.

**Comment by ldidry** [comment]
Je regarderai ça dans une VM, oui, mais ça me semble vraiment bizarre.

**Comment by ldidry** [comment]
Désolé du délai de réponse.

À mon avis, ça ne va pas être possible de rajouter ` BEGIN { unshift @INC, "$FindBin::Bin/../local/lib/perl5/i486-linux-gnu-thread-multi-64int" }` car c'est dépendant de l'architecture du serveur (i486).

Quand tu as testé, est-ce qu'il y avait déjà l'option pour mettre lutim dans un sous-répertoire (http://example.org/lutim/) au lieu de la racine ? Si la réponse est non, il y a des chances que tu doives mettre tes `BEGIN` dans `script/application` à la place de `script/lutim`.

**Comment by maniackcrudelis** [comment]
Oui, en effet c'est un problème auquel on été confronté certains utilisateurs.
J'ai contourné ce problème en modifiant cette ligne en fonction du dossier créé par ```carton install```
https://github.com/maniackcrudelis/lutim_ynh/blob/master/scripts/install#L104-L110

**Comment by ldidry** [comment]
Du coup, on peut fermer ce ticket ?

**Comment by maniackcrudelis** [comment]
Oui sans problème.
