### ISSUE TITLE
Pas de suppression des images obsolètes

### ISSUE THREAD

**Issue by maniackcrudelis** [ldidry/lutim#60]
Salut,

Je rencontre un petit problème sur la suppression des images dont la période de validité est dépassée.
J'ai récemment fait un essai avec cette image:
https://crudelis.fr/lutim/eqqgLSxX

Sa date de validité était de 24h, enregistrée dimanche à midi. Elle aurait donc du être supprimée hier dans la nuit à l'exécution du cron.
En exécutant manuellement la commande ```sudo /usr/local/bin/carton exec script/lutim cron cleanfiles``` depuis ```/var/www/lutim```, carton travaille pendant quelques seconde puis se termine sans message d'erreur. Et sans supprimer l'image non plus...
Peut-on vérifier le contenu de la bdd?
Je précise que cet essai fait suite à une autre image que j'ai supprimé manuellement après plusieurs jours.

J'en profite pour ajouter qu'un petit récapitulatif des images hébergées et de leur état serait bien pratique ;)

**Comment by ldidry** [comment]
Pour vérifier dans la bdd, il faut faire :

```
sqlite3 lutim.db
.mode column
.headers on
select * from lutim where short = 'eqqgLSxX';
```

Est-ce que la commande est bien lancée avec un utilisateur qui a les droits sur le répertoire d'upload (`files`) ?

**Comment by maniackcrudelis** [comment]
Plantage complet du fichier init.d après le passage à Jessie...
Donc j'ai réinstallé et je refais un nouvel essai.

L'image n'était plus dans la base de donnée (la précédente), mais le dossier files avait également disparu (!).
Le dossier files appartient à www-data et le cron exécute la commande avec ces mêmes droits.
J'attends jeudi pour vérifier la suppression de l'image...

**Comment by ldidry** [comment]
Tu peux te baser sur <https://git.framasoft.org/luc/lstu/blob/master/utilities/lstu.service> pour te faire un service systemd.

C'est étrange que l'image ne soit plus dans la bdd vu que même quand on la supprime, il reste un enregistrement dans la bdd (normalement). Et je ne comprends absolument pas pourquoi `files` aurait été supprimé oO

**Comment by maniackcrudelis** [comment]
Je me demandais ce qu'étais lstu, mais en fait c'est un autre de tes projets!
D'ailleurs, je débarque, je viens juste de me rendre compte que tu étais le sys admin de framasoft! M'aura fallu du temps...

J'ai jeté un coup d'oeil au service systemd, c'est pas limpide là tout de suite comme ça, mais ça semble assez simple à mettre en place.
Je devrais facilement pouvoir faire un service pour lutim. Mais je ne suis pas certain en revanche que Yunohost le prenne en charge en tant que service.
Toutefois, pour le moment du moins, la réinstallation a rétabli le fonctionnement du service.

**Comment by ldidry** [comment]
Ah oui, c'est vrai, yunohost.

**Comment by maniackcrudelis** [comment]
Et oui, c'est pour ça que je m'arrache tant les cheveux, ça ne doit pas fonctionner que pour moi, mais pour n'importe quel user lambda voulant utiliser lutim sur Yunohost sans savoir comment ça marche.

**Comment by maniackcrudelis** [comment]
L'image n'a pas été supprimée par le cron. Le cron ne fournit aucun log d'erreur.

La commande du cron est la suivante:
```0 6 * * * www-data cd "/var/www/lutim/" && /usr/local/bin/carton exec script/lutim cron cleanfiles```

En testant manuellement
```sudo -u www-data /usr/local/bin/carton exec script/lutim cron cleanfiles```
Pas d'erreur, pas de suppression de l'image, elle est toujours dans la base de donnée. Le dossier files et l'image appartiennent à www-data

Hum... Dans la base de donnée, "delete_at_day" est à 0, il ne devrait pas contenir la date de suppression!?

**Comment by ldidry** [comment]
Il devrait contenir le nombre de jours avant de supprimer l'image. Si tu le mets manuellement à 1 dans la bdd et que tu lances le cron, est-ce que ça supprime bien l'image ?

**Comment by maniackcrudelis** [comment]
Comment je modifie ça dans la bdd?

**Comment by maniackcrudelis** [comment]
Je viens d'ajouter une image avec un délai de 7 jours, delete_at_day est quand même à 0 pour cette image.

**Comment by ldidry** [comment]
Ah, donc c'est une autre sorte de problème.

**Comment by ldidry** [comment]
Tu fais tourner ton lutim sur une VM ou y a moyen que j'aille tester l'interface ?

**Comment by maniackcrudelis** [comment]
Ah! Attend, l'interface est privée
Souviens toi le temps qu'on à passé là dessus!

**Comment by maniackcrudelis** [comment]
Je fais sauter ça

**Comment by ldidry** [comment]
Oui, oui, je me souviens :D

**Comment by maniackcrudelis** [comment]
Ça devrait être bon:
https://crudelis.fr/lutim/

**Comment by ldidry** [comment]
Tu peux me donner ce que donne `select delete_at_day where short = 'u8COxzoy';` steup ?

**Comment by ldidry** [comment]
Sinon, pour changer le delete_at_day dans la bdd, c'est `update lutim set delete_at_day=1 where short='truc';`

**Comment by maniackcrudelis** [comment]
Error: no such column: delete_at_day

Avec la commande précédente je vois que delete_at_day est toujours à 0 sur ton image

**Comment by maniackcrudelis** [comment]
Ok, en modifiant la valeur à 1, l'image a bien été supprimée par la commande manuelle. Le problème vient donc bien de cette valeur qui reste à 0.

**Comment by ldidry** [comment]
ça c'est bizarre.

**Comment by ldidry** [comment]
t'en es à quel commit sur ta version de lutim ?

**Comment by maniackcrudelis** [comment]
Le change file est à:
    0.7  2015-?
    	- Allow Lutim to be on a sub-directory (like http://example.org/lutim/) (#46)
    	- Remove deprecated (due to typo) option "provisionning".

**Comment by ldidry** [comment]
Ah merde. un bug. Va falloir régler ça vite.

**Comment by maniackcrudelis** [comment]
Par contre je ne retrouve pas ce changelog dans tes commit...

**Comment by ldidry** [comment]
Ce que contient `Changes` n'est pas forcément les messages des commits. Je le fais à la main.

**Comment by maniackcrudelis** [comment]
Non, mais j'espérais retrouvé la date de changement du fichier. Tant pis.
Je pense être au commit du Fix 46
https://github.com/ldidry/lutim/commit/c8ee581bcb4d1f00c37e010c50d474979c7dc48d
Qui avait été fait sur la branche proxy le 6 janvier 2015.

C'est lui qui permettait l'usage en sous-dossier.
Depuis j'ai pas mis à jour, en attendant une release.

**Comment by ldidry** [comment]
Tu peux mettre à jour steup ? Ça devrait être bon là.

**Comment by ldidry** [comment]
N'oublie pas de refaire `carton install`

**Comment by maniackcrudelis** [comment]
Ah bon?

Et donc je passe sur le commit de master

**Comment by ldidry** [comment]
Ah oui, la branche proxy a été intégrée à master :smile:

**Comment by maniackcrudelis** [comment]
OK, la mise à jour est faite.
Et la valeur est bien passée à 1.
D'ailleurs, ça veut dire que la durée n'est pas de 24h, mais de 1 jour.
Le cron va s'exécuter à 6h demain matin, et l'image va sauter avant les 24h. Peut-être qu'en indiquant 1 jour ce serait plus clair.

J'attends de voir maintenant si mes images seront bien supprimées demain, pour valider le cron.

Merci de ta réactivité ;)

**Comment by ldidry** [comment]
Ah zut, j'ai pas précisé que le cron cleanfiles doit être effectué plus d'une fois par jour. 
Bon, bah je rajouterai ça dans la doc (https://git.framasoft.org/luc/lutim/issues/6).

**Comment by maniackcrudelis** [comment]
Mais si je le fais plusieurs fois pas jour, l'image sera supprimée encore plus vite!
Là j'ai uploadé une image avec une validité de 24h, la valeur est déjà à 1. Dés que le cron sera exécuté, l'image sera supprimée.
Ou alors j'ai mal compris?

**Comment by ldidry** [comment]
Oui, tu as mal compris :wink: dans le cron, je sélectionne les images à supprimer un peu comme ça :
```
SELECT * from lutim WHERE enabled = 1 AND (delete_at_day * 86400) < (NOW() - created_at) AND delete_at_day != 0
```
C'est à dire que je prends le timestamp de maintenant, j'enlève le timestamp de la création du fichier, et je regarde si ce résultat est supérieur à max_jours * un jour en secondes.

**Comment by maniackcrudelis** [comment]
Ah ok, je vois.
Et comme l'image datait de quelques jours, en indiquant 1 dans la bdd, on avait une différence de plusieurs jours par rapport à la création. Donc ça dépassait un jour.
Ok je comprend ;)

**Comment by maniackcrudelis** [comment]
Tu préconises une vérification à quelle fréquence?

**Comment by ldidry** [comment]
L'idéal serait toutes les minutes, après je sais pas trop quel peut être l'impact en terme de performances. Ça doit dépendre de la machine. Essaye toutes les 5 minutes, ça devrait le faire.

**Comment by ldidry** [comment]
mais non ! quel con ! Y a pas besoin ! Explication : quand une personne va voir l'image, lutim vérifie qu'elle n'est pas expirée :-)

**Comment by ldidry** [comment]
enfin, qu'elle n'a pas dépassé la date limite de consommation quoi.

Le cleanfiles, c'est pour faire le ménage dans les images qui ne sont pas appelées (et donc qui ne sont pas expirées par une visite).

**Comment by maniackcrudelis** [comment]
Oh c'est intéressant ça!
Je vérifierais ça demain alors.

Au final, un check 1 fois par jour est bien suffisant alors.

**Comment by ldidry** [comment]
Donc une fois par jour, c'est plus que suffisant.

**Comment by ldidry** [comment]
ouaip.

**Comment by ldidry** [comment]
Mais tu peux tricher en mettant un created_at très bas dans la base de données.

```
update lutim set created_at = 1 where short = 'truc';
```

**Comment by maniackcrudelis** [comment]
Si ça reste dans la bdd après, autant supprimer manuellement l'image.
D'ailleurs, la bdd est cleanée quand même de temps en temps?

**Comment by ldidry** [comment]
Non, on garde les enregistrements des anciennes images pour éviter de réutiliser une ancienne adresse (imagine que tu postes une image de bisounours dans un forum et qu'un ou deux ans après ce soit du porn :stuck_out_tongue: Ça par contre, si on chiffre les images, ça ne peut pas arriver (peu de chances de récupérer un ID d'image anciennement existante **et** la même clé de chiffrement). Et aussi pour conserver l'IP de l'envoyeur pendant un temps configurable (obligations légales, tout ça). Avec cleanbdd, ça supprime les IPs au bout du délai configurable.

**Comment by maniackcrudelis** [comment]
OK, effectivement, je comprend.
Mais ça peut pas devenir gênant au niveau des performances de la bdd sur une instance très sollicité? Comme la tienne.

**Comment by ldidry** [comment]
Non, je pense que ça ira très bien : <https://www.sqlite.org/whentouse.html> regarde la partie "website". Moi je n'ai qu'une table, je tape dans des colonnes indexées proprement, donc ça devrait carrément tenir grave.

**Comment by maniackcrudelis** [comment]
Super

Et tout fonctionne parfaitement maintenant. Enfin j'attends quand même demain pour en être sûr ;)

**Comment by ldidry** [comment]
Je ferme, vu que ça fait un mois qu'on a résolu le problème et que tu ne t'es pas manifesté pour dire que ça débloquait.

**Comment by maniackcrudelis** [comment]
Désolé, je n'ai pas pris le temps de répondre car j'ai vérifié bien plus tardivement que prévu.
Et j'ai du adapter mon cron.

Mais tout fonctionne correctement ;)
