### ISSUE TITLE
Error in SQLite

### ISSUE THREAD

**Issue by Phyks** [ldidry/lutim#61]
Hi,

I have the following error in my log, preventing me from accessing my lutim instance:
```
[Sat May 23 22:59:55 2015] [error] DBD::SQLite::db selectrow_array failed: attempt to write a      readonly database at (eval 293) line 54.
```

All I did was delete the database and empty the `files/` folder, to recreate it automatically after an update, as I did not see at first the update part in the README file.

Unix permissions on the database should be ok.

Thanks

**Comment by ldidry** [comment]
Who is the user set in lutim.conf and what are the permissions of the directory you installed Lutim into (/var/www/lutim or something like that)? I think there the directory belongs to a user and don't allow another user to write in.

**Comment by Phyks** [comment]
Hmmm, permissions should be ok. Lutim is started as `www-data` and permissions should be set for `www-data`. Not sure exactly about what was happening, but using the service unit and starting lutim with it, being logged in as root, seems to block everything. Starting the service manually as `www-data` solved it… This problem is still very strange for me :/
