### ISSUE TITLE
utiliser lutim dans sharex

### ISSUE THREAD

**Issue by call5** [ldidry/lutim#62]
bonjour, j'utilise sharex pour faires des captures d'écran et j'aime beaucoup le service lut.im pour l'hébergement et donc j'aimerais pouvoir l'utiliser dans sharex comme service d'upload d'image personnalisé. voici un exemple de formulaire ( voir capture ) à remplir pour pouvoir s'en servir, serait'il possible de m'indiquer les parametre à mettre pour celà. merci d'avance.

![sharex](http://i.imgur.com/wfnbyYF.png)

**Comment by ldidry** [comment]
URL : `https://lut.im` en POST
paramètres : 
* `file` : le fichier (mais je sais pas comment on spécifie ça dans sharex). Obligatoire
* `format` : `json` Obligatoire si on veut avoir une réponse en json
* `delete-day` : le nombre de jour de validité de l'image. Optionnel. Si c'est 0, ça restera indéfiniment
* `first-view` : supprimer à la première vue (si différent de 0, ça sera supprimé à la première vue, sans effet si c'est 0). Optionnel.

Pour la réponse : 
* `msg` : table de hachage contenant :
    * `short` : à ajouter à `https://lut.im/` pour avoir l'URL de l'image
    * `real_short` : identifiant de l'image sans la clé de chiffrement
    * `thumb` : miniature de l'image encodée en base64
    * `token` : jeton de modification ou de suppression. Pour supprimer une image, il faut utiliser l'URL `https://lut.im/d/$real_short/$token` (en remplaçant `$real_short` et `$token` par les valeurs renvoyées par l'API.
    * `filename` : le nom de l'image uploadée
* `success` : `true` ou `false` selon que l'upload a fonctionné ou pas

Dis-moi si ça a fonctionné, je ne connais pas du tout ce logiciel.

**Comment by ldidry** [comment]
Pas de réponse un mois après. Je ferme le ticket, sens-toi libre de l'ouvrir de nouveau si ça ne fonctionne pas.
