### ISSUE TITLE
Add markdown code to copy/paste it into my issues

### ISSUE THREAD

**Issue by nicosomb** [ldidry/lutim#66]
I use lutim to host my issues pictures (like here https://github.com/wallabag/wallabag/pull/1400). And I never remember the markdown code for pictures. 
Maybe you can add it to make my like easier ;-)

**Comment by ldidry** [comment]
Please post your issue on https://git.framasoft.org/luc/lutim/issues :p 

On verra ;-)

**Comment by ldidry** [comment]
Fixed in 6fab43b15b8e58ce7ce3fd1686a4f2718f491f1b

**Comment by nicosomb** [comment]
Thank you! Still not in production on lut.im? :-)

**Comment by ldidry** [comment]
Nope, I need to tranlate some strings, and pootle is a pain in the ass for updating the main file and update the translation from the main file.
